### ISSUE TITLE
[Fix] iOS - 디자인 수정

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#101]
## 🎾  Issue

iOS 디자인 사항을 수정합니다.

## 📝  To-do

- [x] 온보딩 내 정보 입력하기 뷰 레이아웃 수정
- [x] 메인뷰 타이틀 텍스트 행간 조절
- [x] 메인뷰 링차트 내부 텍스트 수정
- [x] 세팅뷰 레이아웃 수정
