### ISSUE TITLE
[Feat]WatchOS-스윙 횟수뷰 관련 기능 완성

### ISSUE THREAD

**Issue by Taerogrammer** [DeveloperAcademy-POSTECH/MC3-Team9-F4#104]
## 🎾  Issue

- 스윙 횟수 관련 뷰 기능 완성하기

## 📝  To-do

- [x] 스윙 시 퍼펙트, 배드, 포핸드, 백핸드 구분 후 데이터 추가
- [x] <Design> 목표 스윙 도달 시 '달성 완료!' 1.5초 띄우기
- [x] <Design> '달성 완료!' 후 연습 끝내기 여부 물어보는 뷰 만들기
- [x] <Feat> 버튼 클릭으로 뷰 이동
