### ISSUE TITLE
[Setting]WatchOS - 백그라운드 모드 관련 세팅

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MC3-Team9-F4#114]
## 🎾  Issue
- 스윙 감지가 백그라운드에서도 이루어지도록 하기 위한 기본 세팅
  - Background Modes Capability 추가
  - HealthKit의 HKWorkoutSession으로 운동 세션을 열어주면 백그라운드에서도 동작함

## 📝  To-do

- [x] Background Modes Capability 추가
- [x] WorkoutManager.swift 파일 추가
- [x] Workout session 괸련 코드 작성
