### ISSUE TITLE
[Feat] watchOS 연습 종료 확인 화면

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MC3-Team9-F4#124]
## 🎾  Issue
- 연습 종료 확인 화면 작업
<img width="149" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MC3-Team9-F4/assets/89764127/dfbbc65f-7497-48a3-afa7-93fba95c2e2d">

## 📝  To-do
- [x] 남은 스윙 횟수에 따른 분기 처리
- [x] 실시간 시간 표시 뷰 추가
- [x] 백그라운드 모드에서 subseconds 가려지도록 설정
