### ISSUE TITLE
[Feat] watchOS 운동 데이터 iOS로 전송

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MC3-Team9-F4#125]
## 🎾  Issue
- watchOS에서 운동 관련 데이터를 iOS로 전송해줘야함
  - 칼로리
  - 운동 시간
  - 운동일
  - (심박수) -> 합의 필요

## 📝  To-do
- [x] 운동 종료 시 HealthResultInfo 모델에 Workout 데이터 저장
- [x] 운동 시간 분 단위로 받도록
- [ ] 운동일 Timezone 현재 위치 기준으로
- [x] 운동일 운동 시작 시점 기준으로
- [x] iOS로 전송시키기
