### ISSUE TITLE
[Feat] iOS - 프로필 사진 저장 로직 CoreData 사용하는 방식으로 수정

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#140]
## 🎾  Issue

프로필 사진을 앱 차원에서 저장하고, 불러오는 로직을 구현

## 📝  To-do

- [x] CoreData 어트리뷰트 변경
- [x] UserModel 로직 변경
- [x] SettingView, OnboardingView에 적용(뷰에 데이터 띄우기)
