### ISSUE TITLE
[Fix] Onboarding 터치 불가능 이슈 해결

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#158]
## 🎾  Issue

Onboarding 마지막 페이지에서 리스트 탭이 안되는 문제 해결

## 📝  To-do

- [x] 온보딩 마지막 뷰 리스트 터치 문제 해결
- [x] 프로필 입력 원 줄어드는 버그 해결
- [x] 다음 버튼 패딩값 줄어드는 문제 해결
- [x] 프로필 입력 사진 선택하고 키보드 올려면 사진 안 줄어드는 문제 해결
