### ISSUE TITLE
[Feat] 세팅뷰 - 세팅 메인뷰 

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#21]
## 🎾  Issue

세팅뷰 중 세팅 메인뷰를 구현합니다.

## 📝  To-do

- [x]  기본 컴포넌트 배치(레이아웃)
- [x]  내정보 수정, 알림 설정뷰와 연결
- [ ]  프로필 사진 데이터 저장 업로드 구현
