### ISSUE TITLE
[feature] 작업에 필요한 기본 컴포넌트, 익스텐션 추가 작업

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#3]
## 🎾  Issue

- 작업에 필요한 기본 컴포넌트, 익스텐션을 구현합니다.

## 📝  To-do

- [ ]  중복 컴포넌트 일체화
- [ ]  컬러 익스텐션 추가
- [ ]  컬러 에셋 추가
- [ ]  폰트 익스텐션 추가
