### ISSUE TITLE
[Design] 디자인 오류 수정

### ISSUE THREAD

**Issue by DhKimy** [DeveloperAcademy-POSTECH/MC3-Team9-F4#59]
## 🎾  Issue

디자인이 완벽하지 않은 곳의 디자인을 수정합니다. 
네비게이션 타이틀 같은 자잘한 작업 들을 진행합니다.

## 📝  To-do

- [x] 테니스 가이드 부분 x 버튼 아래로 내리기
- [x] 모든 뷰 backbutton 커스텀으로 바꾸기
- [x] 프로필 수정 뷰 "저장" 버튼 우측 상단 추가
- [x] 프로필 수정 뷰 "닉네임" 변경 기능 추가
- [x] 포핸드/백핸드 스윙횟수 설정 저장 버튼 텍스트 검정으로 변경
- [x] 인스타그램 버튼 누락 해결
