### ISSUE TITLE
[Feat]WatchOS-WatchConnectivity 연결

### ISSUE THREAD

**Issue by Taerogrammer** [DeveloperAcademy-POSTECH/MC3-Team9-F4#73]
## 🎾  Issue

- 데이터 연결 후 iOS로 전달하기

## 📝  To-do

- [ ]  포핸드, 백핸드 여부
- [ ] 목표 스윙 개수
- [ ] 총 스윙 횟수
- [ ] perfect 횟수
- [ ] HealthKit 데이터 (운동 시간, BPM, kcal)
