### ISSUE TITLE
[Feat] watchOS - 운동 시작 이후 Activity Classifier 모델 동작 처리

### ISSUE THREAD

**Issue by kybeen** [DeveloperAcademy-POSTECH/MC3-Team9-F4#97]
## 🎾  Issue
- 운동 시작 버튼 누른 이후 ML 모델 관련 동작 처리하기

## 📝  To-do

- [x] 시작 버튼 누르면 모델 불러오기
- [x] 시작 버튼 누르면 Device Motion 추적 시작
- [x] 스윙 감지 시 MeasuringView로 넘어가도록 화면 처리
- [x] SwingResultView에 스윙 감지 결과 반영
